### PR TITLE
Pull request to address Ishin save issues

### PR DESCRIPTION
**Pull request by jeottesen**
This is a PR to address the bug I outlined in issue #5. 

While I was debugging it I added a bunch of tests to make sure I wasn't breaking anything. When I had figured it out I felt like expanding the tests to cover everything else with the help of AI. I vetted and fixed all the tests the AI generated of course.

I also used it to create a small script on the side that converts Ishin saves from gamepass to steam and vice versa. I am not sure you want all that but here is a pull request for it all anyway if you do.

### CODE REVIEW

**Comment by GarnetSunset** [comment]
Could we have that integrated into the main script perhaps?

**Comment by jeottesen** [comment]
Yeah, probably after the game detection it could check if it's an ishin save then check for the `--to-steam` or `--to-gamepass` args and call the convert function then. Encrypt or decrypt doesn't really matter in this case.

**Comment by GarnetSunset** [comment]
I'lll look into it! Thanks for the work.

**Comment by jeottesen** [comment]
I can look into it. Especially since I'm dumping a huge set of changes on you. 

On another note, while writing tests I found that the second Gaiden header conflicts with the second Lost Judgement header. I commented out the Lost Judgement header to get the tests to pass at the moment but I would like to know your opinion on how to address it. As the key is the same it doesn't seem like it's too big a deal to mismatch the Lost Judgment save.

**Comment by GarnetSunset** [comment]
Do you mind dropping an example of the ishin saves here?

**Comment by jeottesen** [comment]
Sure here are the saves. They are stored in the repo to use in the end to end tests.
Encrypted:
[test_ik.sav](https://github.com/jeottesen/rgg_save_tool_py/raw/refs/heads/main/saves/test_ik.sav)

Decrypted:
[test_ik.json](https://github.com/jeottesen/rgg_save_tool_py/raw/refs/heads/main/saves/test_ik.json)

**Comment by jeottesen** [comment]
I integrated the platform conversion script into the main script as requested.

**Comment by GarnetSunset** [comment]
I'm starting a new job so I'll have to check this when I have some more free time :)

**Comment by GarnetSunset** [comment]
@jeottesen incredible work on the code! Finally reviewed it. Didn't try your tests because honestly I couldn't get them to run, but pushed up the untested. If you'd like to have those work I'd LOVE to have them.

**Comment by jeottesen** [comment]
Thanks! I updated the tests. 

I was running the tests through vscode so it was all configured for that. I added a config file that will let them be ran from the command line. All you need to do is install pytest with pip then run `pytest` in the project root. It will find the tests and run them automatically.

**Comment by GarnetSunset** [comment]
Incredible work! Thank you so much! I'll be adding you to the Readme :)

**Pull request merged**
